
//#define EXAMPLE_MPEG2PARSER
//#define EXAMPLE_DEBUGNCOMPILATION
//#define EXAMPLE_MACROS
//#define EXAMPLE_VARIABLEARGFUNCTIONS
//#define EXAMPLE_TYPECONVERSION
//#define EXAMPLE_MEMCPYTEST
//#define EXAMPLE_PARSEINDEX
#define EXAMPLE_TASK
//#define EXAMPLE_S64
